### ISSUE TITLE
Erro ao subir aplicação nestjs (não conecta no broker kafka)

### ISSUE THREAD

**Issue by m4t3us89** [codeedu/imersao8#3]
Boa notie pessoal. 
Pois bem, consigo produzir e consumir do broker (kafka) pela aplicação GO, no entanto, ao tentar "subir" o nestjs minha conexão ao broker é recusada conforme print:
![image](https://user-images.githubusercontent.com/32775082/174916373-0ceae865-bfcb-44c4-9526-682ccd3a43da.png)

ps. Sim, já adicionei o host do broker no arquivo hosts
![image](https://user-images.githubusercontent.com/32775082/174916500-d49337c7-d668-4162-85fe-7e59dee4f92c.png)

O mais interessante que eu consigo consumir e produzir normalmente pela app GO. 
Utilizo windows 11 com wsl2, alguém com esse problema especifico ?

**Comment by argentinaluiz** [comment]
Olá @m4t3us89 , tudo bem?

Adicione estas linhas no seu docker-compose.yaml: [https://github.com/codeedu/imersao8/blob/main/nest-api/docker-compose.yaml#L14-L15](https://github.com/codeedu/imersao8/blob/main/nest-api/docker-compose.yaml#L14-L15).

Então, o Nest.js saberá como identificar o host.docker.internal.

Me fale se conseguiu evoluir com isto, ok?

Qualquer dúvida, estamos à disposição.

;)

**Comment by m4t3us89** [comment]
Olá @argentinaluiz, tudo ótimo !?
Obrigado por responder.

Fiz essa alteração  https://github.com/codeedu/imersao8/blob/main/nest-api/docker-compose.yaml#L14-L15 , porém acontece esse outro problema de TSL
![image](https://user-images.githubusercontent.com/32775082/175053218-e331fce9-fb34-40bb-a43c-fa978436c7a3.png)

Isso dá a entender que está tendo algum problema com validação de certificado, sendo que, meu broker ta sendo chamado sem o HTTPS conforme arquivo de ambiente:
![image](https://user-images.githubusercontent.com/32775082/175057143-91d71299-8165-4971-8569-6abc7144fad8.png)

**Comment by argentinaluiz** [comment]
Olá @m4t3us89 , tudo tranquilo!

Sim é isto mesmo. Definimos a conexão com Kafka para trabalhar com TLS, porque quando fizermos o deploy da aplicação e usarmos o Kafka em produção, usamos TLS para conexão.

Para não usar TLS, use estas duas variáveis em branco: [https://github.com/codeedu/imersao8/blob/main/nest-api/.env.example#L6-L7](https://github.com/codeedu/imersao8/blob/main/nest-api/.env.example#L6-L7).

Me fale se conseguiu evoluir com isto, ok?

Qualquer dúvida, estamos à disposição.

;)

**Comment by m4t3us89** [comment]
Bom dia @argentinaluiz ,
Então, eu havia tentado deixar em branco essas variaveis de ambiente, no entanto não havia funcionado.
Consegui resolver, removento a configuração de SSL direto na factory conforme print:
![image](https://user-images.githubusercontent.com/32775082/175296166-92105e7a-979b-44d8-876e-cb9b83bbacfa.png)

Muito obrigado. :)
