### ISSUE TITLE
Erro ao executar docker-compose up

### ISSUE THREAD

**Issue by LeonardoGregoriocs** [codeedu/imersao8#4]
Bom dia! 
Criei os arquivos Dockerfile, docker-compose e também o arquivo entrypoint na pasta .docker, porém ao executar o comando  "docker-compose up", estou tendo o seguinte erro: 

![Captura de tela de 2022-06-22 10-57-29](https://user-images.githubusercontent.com/83976271/175048083-74ddef99-b564-400c-bd16-ee03a5bce085.png)

Tentei até fazer o build através do comando "docker-compose up -d --build", porém tive essa mensagem: 
![Captura de tela de 2022-06-22 11-01-40](https://user-images.githubusercontent.com/83976271/175048469-61cd817f-d064-41b3-9dfe-a02c9f66ee90.png)

Alguém com erro parecido que possa dar uma ajuda? 
Valeu, pessoal!

**Comment by LeonardoGregoriocs** [comment]
Obs. Tentei também alterar a versão do alpine, porém sem sucesso também.

**Comment by m4t3us89** [comment]
Opa @LeonardoGregoriocs , tranquilo kra ?
Verificou se o caminho ta correto ?
Verificou a permissão de leitura do arquivo ?

**Comment by LeonardoGregoriocs** [comment]
Opa! 
Sim, pelo que vi está tudo correto.. Tanto o caminho, quanto a questão de leitura, antes de rodar o "docker-compose up", rodei o comando "chmod +x .docker/entrypoint.sh".

Acredito que seja o AlpineLinux, pois na hora que rodo o comando "docker-compose up -d --build", ele quebra na hora de dar build no 2 step. 

Obs. Tentei até alterar a versão do Alpine, porém sem sucesso.

**Comment by m4t3us89** [comment]
É provável @LeonardoGregoriocs, eu utilizo wsl2  +  ubuntu e não tive esse problema. 
Você pode fazer esse teste:
 Remova esse entrypoint do seu arquivo dcoker-composer, suba o container "docker-compose up -d", se subir, entre no bash do container "docker-compose exec 'nome' bash",  instale as dependencias "npm install" e em seguida suba a aplicação "npm run start:dev".

**Comment by LeonardoGregoriocs** [comment]
Então, tentei desta forma também.. quando tiro o entrypoint e subo o container, ele sobe! Porém na hora de usar o comando "docker-compose exec <nome> bash" para abrir o bash, ele dá uma mensagem de erro novamente. 

Por isso, estou achando que o b.o está no AlpineLinux, pois ao tentar rebuild, ele aparece mensagem de erro: 
![Captura de tela de 2022-06-22 10-00-03](https://user-images.githubusercontent.com/83976271/175108002-33ddd1e1-3317-45de-9187-802313d9c071.png)
![Captura de tela de 2022-06-22 10-26-43](https://user-images.githubusercontent.com/83976271/175108018-90eb5376-43fd-4c32-a429-b4e68de21cc6.png)

**Comment by m4t3us89** [comment]
É, realmente me parece algum problema com a sua distribuição @LeonardoGregoriocs.

**Comment by LeonardoGregoriocs** [comment]
Verifiquei nas Issues do Github do docker-alpine, e em um dos comentários consegui achar uma solução para o problema. Executei o comando abaixo: 
sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

Após isso, dei o comando "docker-compose up" e fez o build normalmente.

**Comment by LeonardoGregoriocs** [comment]
Verifiquei nas Issues do Github do docker-alpine, e em um dos comentários consegui achar uma solução para o problema. Executei o comando abaixo:
sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

Após isso, dei o comando "docker-compose up" e fez o build normalmente.
