### ISSUE TITLE
Erro ao conectar nest com o kafka

### ISSUE THREAD

**Issue by carlosSimplicio** [codeedu/imersao8#6]
Olá, estou tomando esse erro ao tentar conectar o nest com o Kafka

![image](https://user-images.githubusercontent.com/61396166/175795054-039380a1-fde9-427b-b23c-14d7bdc010ff.png)

A config ssl já está comentada, e /etc/hosts está configurado, no entanto não parece resolver o meu problema.

Mesmo baixando a ultima versão do repositório o erro se mantem.

**Comment by argentinaluiz** [comment]
Olá @cEd-moura , tudo bem?

Você conseguiu evoluir com esta questão?

**Comment by carlosSimplicio** [comment]
Fala @argentinaluiz !
Sim, eu precisei comentar a parte de ssl no `main.ts` assim como está no `routes.modeule.ts`.
